function disp_details(id:number,name:string,mail_id?:string) { 
   console.log("ID:", id); 
   console.log("Name",name); 
   
   if(mail_id!=undefined)  
   console.log("Email Id",mail_id); 
}
disp_details(123,"John");
disp_details(111,"mary","mary@xyz.com");

// function addNumbers() {
//    var nums = [];
//    for (var _i = 0; _i < arguments.length; _i++) {
//       nums[_i - 0] = arguments[_i];
//    }
// 	var i;
//    var sum = 0;
	
//    for (i = 0; i < nums.length; i++) {
//       sum = sum + nums[i];
//    }
//    console.log("sum of the numbers", sum);
// }
// addNumbers(1, 2, 3);
// addNumbers(10, 10, 10, 10, 10);

//Generated by typescript 1.8.10
function calculate_discount(price, rate) {
   if (rate === void 0) { rate = 0.50; }
   var discount = price * rate;
   console.log("Discount Amount: ", discount);
}
calculate_discount(1000, 0);
calculate_discount(1000, 0.30);


const myFanc = (a:number, b:number, c:number=8) => {
   return a + b;
}

myFanc(5, 8)